vcenter_hostname: '{{ lookup("env", "VMWARE_HOST") }}'
vcenter_username: '{{ lookup("env", "VMWARE_USER") }}'
vcenter_password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
#vm_name:  '{{ item["Name"] }}'
folder: "/{{ datacenter }}/vm"
datastore_name: []


