---

- name: Read server details from CSV file
  read_csv:
     path: roles/role_disk_space/vars/input.csv
     key: 'Configuration item'
  register: inputList
  delegate_to: localhost

- name: Login into vCenter 
  read_csv:
     path: roles/role_disk_space/vars/vcenter.csv
     key: 'URL'
     user: "{{ vcenter_username }}"
     password: "{{ vcenter_password }}"
  register: login

- name: Get datacenters from vCenter
  uri:
   url: https://{{ vcenter_hostname }}/rest/vcenter/datacenter
   force_basic_auth: yes
   validate_certs: no
   headers:
     Cookie: "{{ login.set_cookie }}"
  register: vDatacenters

- name: Print names of datacenters in the given vCenter
  debug:
   msg: "{{ item.name }}"
  with_items: "{{ vDatacenters.json.value }}" 

- set_fact:
   data_center: "{{ item.name }}"
  with_items: "{{ vDatacenters.json.value }}"

- debug: msg="{{ data_center }}"


- name: Gather datastore details
  vmware_datastore_facts:
   hostname: "{{ vcenter_hostname }}"
   username: "{{ vcenter_username }}"
   password: "{{ vcenter_password }}"
   validate_certs: no
   datacenter: "{{ data_center }}"
  register: info


- name: Get Datastore Name
  set_fact: 
   datastore_name: "{{ datastore_name + [item.name] }}"
  with_items: "{{ info.datastores }}"
 


        

