---
 
   - name: Retrieve Disk Usage
    win_shell: 'Get-PSDrive C | Select-Object Free'
    register: rawcsize

   - name: extract free space
     set_fact:
     free_json: "{{ output.stdout|from_json}}"

   - name:
     debug:
       var: free_json.Free
    
#  # Convert disk size in Gigabytes
  - name: Convert system disk into various formats and export
    vars:
      disk_int: '{{ rawcsize.stdout | int }}'
      disk_gb: '{{ disk_int | int}}'
    debug:
      msg: 'rawcsize.stdout: {{(rawcsize.stdout)}} disk_int: {{(disk_int)}} disk_gb: {{(disk_gb)}}'
      

- 
