---
 
 - name: get disk free space
  win_shell: Get-PsDrive | ConvertTo-Json
  register: output

- name: extract free space
  set_fact:
    free_json: "{{ output.stdout|from_json}}"

- name:
  debug:
    var: free_json.Free
