---

- name: Get disk facts
  win_disk_facts:

- name: Output first disk size
  debug:
    var: ansible_facts.disks[0].size
    
- name: get disk free space
  win_shell: Get-CimInstance -Class CIM_LogicalDisk | Select-Object @{Name="Free Space(GB)";Expression={$_.freespace/1gb}}, DriveType | Where-Object DriveType -EQ '0' 
  register: output
  
- name: extract
  debug:
    var: output
    
    
        

